
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./telemetry/mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./telemetry/prometheus.yml:/etc/prometheus/prometheus.yml
      # THIS ROUTES YOUR DATA STREAMS TO AN M.2 SSD:
      # Steps were:
      # sudo mount /dev/sda2 /mnt/storage
      # sudo mkdir -p /mnt/storage/prometheus_data
      # sudo chown -R 65534:65534 /mnt/storage/prometheus_data
      - /mnt/storage/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d' # Keeps a full rolling year of garden metrics!
    ports:
      - "9090:9090"
    network_mode: "host"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Provision datasource and dashboard providers from versioned files.
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      # Mount a local dashboard directory for drop-in JSON definitions.
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      # Persist Grafana SQLite DB, users, alerts, and runtime state.
      - /mnt/storage/grafana_data:/var/lib/grafana

    # scp /Users/teishadalton-buford/git/wismesh-mqtt-sensors/docker-compose.yaml pi@raspberrypi.local:~/telemetry/docker-compose.yaml
    # rsync -av --progress /Users/teishadalton-buford/git/wismesh-mqtt-sensors/docker-compose.yaml pi@raspberrypi.local:~/telemetry/docker-compose.yaml